{{- include "ffc-helm-library.container-config-map" (list . "ffc-sfi-payment-web.config-map") -}}
{{- define "ffc-sfi-payment-web.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  {{- if .Values.container.googleTagManagerKey }}
  GOOGLE_TAG_MANAGER_KEY: {{ quote .Values.container.googleTagManagerKey }}
  {{- end }}
{{- end -}}
